name: LoadCart
main: io.github.ikbenlike.LoadCart.LoadCart
version: 0.3.2
api-version: 1.16

permissions:
  LoadCart.count:
    description: Allows count commands
    default: true
  LoadCart.remove:
    description: Allows remove commands
    default: op
  LoadCart.ticket:
    description: Allows ticket management commands
    default: op

commands:
  countminecarts:
    description: Count minecarts
    aliases: cmc
    permission: LoadCart.count
    permission-message: You do not have permission!
    usage: /<command>
  countemptycarts:
    description: Count empty minecarts
    aliases: cemc
    permission: LoadCart.count
    permission-message: You do not have permission!
    usage: /<command>
  countutilitycarts:
    description: Count utility carts
    aliases: cumc
    permission: LoadCart.count
    permission-message: You do not have permission!
    usage: /<command>
  removeminecarts:
    description: Remove all loaded minecarts
    aliases: rmc
    permission: LoadCart.remove
    permission-message: You do not have permission!
    usage: /<command>
  removeemptycarts:
    description: Remove all empty loaded minecarts
    aliases: remc
    permission: LoadCart.remove
    permission-message: You do not have permission!
    usage: /<command>
  removeutilitycarts:
    description: Remove all utility minecarts
    aliases: rumc
    permission: LoadCart.remove
    permission-message: You do not have permission!
  removetickets:
    description: Remove all tickets added by this plugin
    aliases: rts
    permission: LoadCart.ticket
    permission-message: You do not have permission!
